spring.application.name=ultrasound-manager
spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:29685/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MseVypnfwxaTCcJxZDruxrHbwXlbspBY
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=${PORT:8080}
jwt.secret=biomedmaint-secret-key-pfe-2026
jwt.expiration=604800000